### ISSUE TITLE
Xcode 15 Sdk sorunu

### ISSUE THREAD

**Issue by strayon** [relateddigital/relateddigital-ios#5]
![image](https://github.com/relateddigital/relateddigital-ios/assets/37001140/2628026e-3ba0-48d4-9a1b-c9bc9a70c343)
Sources>Utilities>Checkbox.swift dosyasındaki    
`@available(swift, obsoleted: 4.1, renamed: "checkboxFillColor", message: "Defaults to a clear color")`
kısmında Xcode 15 özelinde `Stored properties cannot be marked unavailable with '@available' `hatası alınıyor.
Xcode 14.3.1 öncesinde hata mevcut değil.

**Comment by umutalparslan** [comment]
Selamlar @strayon , Bu hatayı 4.0.30 sürümü ile giderdik. iOS 17 ile beraber @available deprecated olduğundan dolayı Xcode 15'de bu hatayı almaktasınız.
